language: node_js
node_js:
- '13'
cache:
  directories:
    - node_modules
before_script: 
  - truffle compile
script:
  - ganache-cli -d -p 8545 --defaultBalanceEther 10000 -a 30 > /dev/null &
  - sleep 5
  - truffle test
